### PR TITLE
EN-27755 Support add/drop computation strategy on existing columns

### PR DESCRIPTION
**Pull request by chitang**

### CODE REVIEW

**Comment by rjmac** [comment]
I'm not fond of this; the contents of a column with a computation strategy are meaningless without the associated strategy.  It's better to do schema modifications than to mess with the computation strategy.

**Comment by chitang** [comment]
Isn't the computation strategy complete?  What is the missing associated strategy?

**Comment by znep** [comment]
I think the issue is they are unlikely to move all at once?
________________________________

**Comment by chitang** [comment]
A backfill looks really complicated especially if we don't want to re-geocode with an incompatible cache.

**Comment by chitang** [comment]
The complexity is additive and basically boilplate, not multiplicative.

**Comment by chitang** [comment]
probably can restrict this for migration only and revert once migration is over.

**Comment by rjmac** [comment]
(fwiw the code itself looks good; convince me that the approach as a whole works well and I'll happily :+1: this)

**Pull request merged**
