### PR TITLE
Resync API

### PR DESCRIPTION
**Pull request by zachlefevre**

### CODE REVIEW

**Review by rozap — APPROVED** [review]
:ship: we can add the not-found case later

**Review by rozap — CHANGES_REQUESTED** [review]
wait actually - we should maybe add that case first. i'm not sure what the behavior will be if we add random stuff to the secondary manifest this way...

one weird case: there's dataset `A` and it gets soft deleted, then resync gets called on `A`...that may do weird stuff. so we may want to do the lookup of the thing and make sure it's in a state that can be resynced, before we poke the manifest.

**Comment by zachlefevre** [comment]
We'll never add a record to the DB that isn't already there, since this is an update.
We can only perform the update if pending_drop is false. I assume (and have not tested) the secondary will stop receiving events and resyncs if the dataset is pending a drop, so updating the manifest will have no effect.

**Comment by rozap** [comment]
yea, it wouldn't be a problem in hard deletes, but should we have a `WHERE not pending_drop` in that update query?

**Review by rozap — APPROVED** [review]

**Pull request merged**
