### PR TITLE
EN-3886: Change /manifest/secondaries-of-dataset

### PR DESCRIPTION
**Pull request by aerust**
Enpoint now includes:
 - version of dataset in truth
 - map from secondary store ids to version
 - feedback secondary stores

### CODE REVIEW

**Comment by aerust** [comment]
- Still need to test this
- Need to double check that this endpoint isn't being used by something

**Comment by rjmac** [comment]
lgtm pending the todo list above

**Comment by aerust** [comment]
Okay, tested it locally, and all seems well. Now just waiting on checking sumo again.

**Comment by aerust** [comment]
Checked sumo with query `*"secondaries-of-dataset"*` and nothing came back (other than queries I made).

**Pull request merged**
