### PR TITLE
Do feedback-secondary check on copy operations

### PR DESCRIPTION
**Pull request by rjmac**

### CODE REVIEW

**Comment by aerust** [comment]
Looks good to me. I'd like to test it when I get a chance. Does this need to wait on my branch being merged?

**Comment by rjmac** [comment]
You should probably merge it directly into your branch (see the "rjmac wants to merge..." line at the top of the PR page)

**Comment by aerust** [comment]
Oh, okay cool.

**Comment by aerust** [comment]
Okay, cherry picked both commits onto my branch instead of merging. Going to close the pull request. I'll leave it to you to delete the branch.

**Pull request closed without merging**
